"""initial

Revision ID: 264d5d3a9aeb
Revises: 
Create Date: 2026-06-08 04:55:32.222305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264d5d3a9aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'WALLET', 'NETBANKING', name='paymentmethod'), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('daily_limit', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_type', sa.Enum('ECOMMERCE', 'FOOD', 'TRAVEL', 'GAMING', 'RETAIL', 'FINTECH', name='businesstype'), nullable=False),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktier'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'WALLET', 'NETBANKING', name='paymentmethod'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'BLOCKED', 'REFUNDED', name='transactionstatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktier'), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('gateway_used', sa.String(), nullable=True),
    sa.Column('gateway_fee', sa.Float(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bnpl_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate_pa', sa.Float(), nullable=True),
    sa.Column('emi_amount', sa.Float(), nullable=True),
    sa.Column('total_interest', sa.Float(), nullable=True),
    sa.Column('total_payable', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DEFAULTED', name='bnplstatus'), nullable=True),
    sa.Column('repayment_schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('FRAUD', 'DUPLICATE', 'NOT_RECEIVED', 'WRONG_AMOUNT', name='disputereason'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RAISED', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', name='disputestatus'), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('raised_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    op.drop_table('bnpl_loans')
    op.drop_table('transactions')
    op.drop_table('merchants')
    op.drop_table('users')
    op.drop_table('payment_routes')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###